<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">

<head>

<meta charset="utf-8" />
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />




<title>Statistical Analysis</title>

<script src="site_libs/jquery-1.11.3/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/bootstrap.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>
<link href="site_libs/font-awesome-5.1.0/css/all.css" rel="stylesheet" />
<link href="site_libs/font-awesome-5.1.0/css/v4-shims.css" rel="stylesheet" />

<style type="text/css">code{white-space: pre;}</style>
<style type="text/css">
  pre:not([class]) {
    background-color: white;
  }
</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>



<style type="text/css">
h1 {
  font-size: 34px;
}
h1.title {
  font-size: 38px;
}
h2 {
  font-size: 30px;
}
h3 {
  font-size: 24px;
}
h4 {
  font-size: 18px;
}
h5 {
  font-size: 16px;
}
h6 {
  font-size: 12px;
}
.table th:not([align]) {
  text-align: left;
}
</style>




<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
code {
  color: inherit;
  background-color: rgba(0, 0, 0, 0.04);
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
</style>


<style type="text/css">
/* padding for bootstrap navbar */
body {
  padding-top: 51px;
  padding-bottom: 40px;
}
/* offset scroll position for anchor links (for fixed navbar)  */
.section h1 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h2 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h3 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h4 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h5 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h6 {
  padding-top: 56px;
  margin-top: -56px;
}
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #ffffff;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script>
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark it active
  menuAnchor.parent().addClass('active');

  // if it's got a parent navbar menu mark it active as well
  menuAnchor.closest('li.dropdown').addClass('active');
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  background: white;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "&#xe258;";
  border: none;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->




</head>

<body>


<div class="container-fluid main-container">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">HOME</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="overview.html">Overview</a>
</li>
<li>
  <a href="report_web.html">Report</a>
</li>
<li>
  <a href="plotly.html">Plots</a>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li>
  <a>
    <span class="fa fa-video fa-lg"></span>
     
  </a>
</li>
<li>
  <a href="https://github.com/amzhao/jacab_p8105final">
    <span class="fa fa-github fa-lg"></span>
     
  </a>
</li>
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div class="fluid-row" id="header">



<h1 class="title toc-ignore">Statistical Analysis</h1>

</div>


<p>###Importing and cleaning EMS data in NYC:</p>
<pre class="r"><code>ems_data_clean = read.csv(&quot;./data/EMS_Incident_Dispatch_Data.csv&quot;) %&gt;%
  select(INITIAL_SEVERITY_LEVEL_CODE, FINAL_SEVERITY_LEVEL_CODE, INITIAL_CALL_TYPE,
         DISPATCH_RESPONSE_SECONDS_QY, INCIDENT_TRAVEL_TM_SECONDS_QY, HELD_INDICATOR, BOROUGH,
         ZIPCODE, INCIDENT_DISPOSITION_CODE, INCIDENT_DATETIME) %&gt;% 
  janitor::clean_names() %&gt;% 
  separate(col = incident_datetime, into = c(&#39;date&#39;, &#39;time&#39;), sep = &#39; &#39;) %&gt;% 
  separate(col = date, into = c(&quot;month&quot;,&quot;day&quot;), sep = &#39;/&#39;) %&gt;% 
  mutate(month = factor(month, levels = c(&quot;01&quot;, &quot;02&quot;, &quot;03&quot;, &quot;04&quot;, &quot;05&quot;, &quot;06&quot;, &quot;07&quot;, &quot;08&quot;, &quot;09&quot;, &quot;10&quot;, &quot;11&quot;, &quot;12&quot;), labels = c(&quot;Jan&quot;, &quot;Feb&quot;, &quot;Mar&quot;, &quot;Apr&quot;, &quot;May&quot;, &quot;June&quot;, &quot;Jul&quot;, &quot;Aug&quot;, &quot;Sept&quot;, &quot;Oct&quot;, &quot;Nov&quot;, &quot;Dec&quot;), ordered = TRUE)) %&gt;% 
  mutate(arrival_outcome = ifelse(incident_disposition_code == &quot;83&quot;, &quot;dead&quot;, &quot;alive&quot;),
         arrival_outcome = recode_factor(arrival_outcome, `0` = &quot;alive&quot;, `1` = &quot;dead&quot;),
         initial_severity_level_code = factor(initial_severity_level_code, 
 levels = c(&quot;1&quot;, &quot;2&quot;,&quot;3&quot;, &quot;4&quot;, &quot;5&quot;, &quot;6&quot;, &quot;7&quot;, &quot;8&quot;, &quot;9&quot;), ordered = TRUE),
         final_severity_level_code = factor(final_severity_level_code, 
                                            levels = c(&quot;1&quot;, &quot;2&quot;, &quot;3&quot;, &quot;4&quot;, &quot;5&quot;, &quot;6&quot;, &quot;7&quot;, &quot;8&quot;), ordered = TRUE), 
         held_indicator = recode(held_indicator, &quot;N&quot; = &quot;no&quot;, &quot;Y&quot; = &quot;yes&quot;)) %&gt;%
  mutate(neighbourhood = recode(zipcode, &quot;10026&quot; = &quot;central harlem&quot;, &quot;10027&quot; = &quot;central harlem&quot;, &quot;10030&quot; = &quot;central harlem&quot;, &quot;10037&quot; = &quot;central harlem&quot;, &quot;10039&quot; = &quot;central harlem&quot;, &quot;10001&quot; = &quot;chelsea and clinton&quot;, &quot;10001&quot; = &quot;chelsea and clinton&quot;, &quot;10011&quot; = &quot;chelsea and clinton&quot;, &quot;10018&quot; = &quot;chelsea and clinton&quot;, &quot;10019&quot; = &quot;chelsea and clinton&quot;, &quot;10020&quot; = &quot;chelsea and clinton&quot;, &quot;10036&quot; = &quot;chelsea and clinton&quot;,  &quot;10029&quot; = &quot;east harlem&quot;, &quot;10035&quot; = &quot;east harlem&quot;, &quot;10010&quot; = &quot;gramercy park and murray hill&quot;, &quot;10016&quot; = &quot;gramercy park and murray hill&quot;, &quot;10017&quot; = &quot;gramercy park and murray hill&quot;, &quot;10022&quot; = &quot;gramercy park and murray hill&quot;, &quot;10012&quot; = &quot;greenwich village and soho&quot;, &quot;10013&quot; = &quot;greenwich village and soho&quot;, &quot;10014&quot; = &quot;greenwich village and soho&quot;, &quot;10004&quot; = &quot;lower manhattan&quot;, &quot;10005&quot; = &quot;lower manhattan&quot;, &quot;10006&quot; = &quot;lower manhattan&quot;, &quot;10007&quot; = &quot;lower manhattan&quot;, &quot;10038&quot; = &quot;lower manhattan&quot;, &quot;10280&quot; = &quot;lower manhattan&quot;, &quot;10002&quot; = &quot;lower east side&quot;, &quot;10003&quot; = &quot;lower east side&quot;, &quot;10009&quot; = &quot;lower east side&quot;, &quot;10021&quot; = &quot;upper east side&quot;, &quot;10028&quot; = &quot;upper east side&quot;, &quot;10044&quot; = &quot;upper east side&quot;, &quot;10065&quot; = &quot;upper east side&quot;, &quot;10075&quot; = &quot;upper east side&quot;, &quot;10128&quot; = &quot;upper east side&quot;, &quot;10023&quot; = &quot;upper west side&quot;, &quot;10024&quot; = &quot;upper west side&quot;, &quot;10025&quot; = &quot;upper west side&quot;, &quot;10031&quot; = &quot;inwood and washington heights&quot;, &quot;10032&quot; = &quot;inwood and washington heights&quot;, &quot;10033&quot; = &quot;inwood and washington heights&quot;, &quot;10034&quot; = &quot;inwood and washington heights&quot;, &quot;10040&quot; = &quot;inwood and washington heights&quot; )
  ) %&gt;%  
  drop_na(neighbourhood) %&gt;% 
    select(-incident_disposition_code) </code></pre>
<p>###t-test and ANOVA:</p>
<pre class="r"><code>t.test(ems_data_clean$incident_travel_tm_seconds_qy/60 ~ ems_data_clean$arrival_outcome, na.rm = FALSE)</code></pre>
<pre><code>## 
##  Welch Two Sample t-test
## 
## data:  ems_data_clean$incident_travel_tm_seconds_qy/60 by ems_data_clean$arrival_outcome
## t = 51.493, df = 2179.8, p-value &lt; 2.2e-16
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  3.767308 4.065614
## sample estimates:
## mean in group alive  mean in group dead 
##            8.827289            4.910828</code></pre>
<pre class="r"><code>res.aov = aov(incident_travel_tm_seconds_qy/60 ~ neighbourhood, data = ems_data_clean)
# Summary of the analysis
summary(res.aov) </code></pre>
<pre><code>##                   Df   Sum Sq Mean Sq F value Pr(&gt;F)    
## neighbourhood      9   311078   34564   548.7 &lt;2e-16 ***
## Residuals     334634 21077737      63                   
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>t-test: - for those alive: average incident response time = 8.83 minutes - for those dead: average incident response time = 4.91 minutes Since the p-value &lt;</p>
<p>Anova: Since the p-value is less than 0.05, we know there are statistically significant differneces between the mean incident travel time in seconds between neighborhoods.</p>
<p>###Logistic Regression Model and Results Table:</p>
<pre class="r"><code>model = glm(arrival_outcome ~ incident_travel_tm_seconds_qy + initial_severity_level_code + neighbourhood, data = ems_data_clean, family = binomial())

model %&gt;% 
  broom::tidy() %&gt;% 
  mutate(OR = exp(estimate)) %&gt;%
  select(term, log_OR = estimate, OR, p.value) %&gt;% 
  knitr::kable(digits = 3)</code></pre>
<table>
<thead>
<tr>
<th style="text-align:left;">
term
</th>
<th style="text-align:right;">
log_OR
</th>
<th style="text-align:right;">
OR
</th>
<th style="text-align:right;">
p.value
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
(Intercept)
</td>
<td style="text-align:right;">
-7.475
</td>
<td style="text-align:right;">
0.001
</td>
<td style="text-align:right;">
0.696
</td>
</tr>
<tr>
<td style="text-align:left;">
incident_travel_tm_seconds_qy
</td>
<td style="text-align:right;">
0.000
</td>
<td style="text-align:right;">
1.000
</td>
<td style="text-align:right;">
0.043
</td>
</tr>
<tr>
<td style="text-align:left;">
initial_severity_level_code.L
</td>
<td style="text-align:right;">
-9.744
</td>
<td style="text-align:right;">
0.000
</td>
<td style="text-align:right;">
0.906
</td>
</tr>
<tr>
<td style="text-align:left;">
initial_severity_level_code.Q
</td>
<td style="text-align:right;">
-1.494
</td>
<td style="text-align:right;">
0.224
</td>
<td style="text-align:right;">
0.986
</td>
</tr>
<tr>
<td style="text-align:left;">
initial_severity_level_code.C
</td>
<td style="text-align:right;">
-6.554
</td>
<td style="text-align:right;">
0.001
</td>
<td style="text-align:right;">
0.921
</td>
</tr>
<tr>
<td style="text-align:left;">
initial_severity_level_code^4
</td>
<td style="text-align:right;">
-1.833
</td>
<td style="text-align:right;">
0.160
</td>
<td style="text-align:right;">
0.966
</td>
</tr>
<tr>
<td style="text-align:left;">
initial_severity_level_code^5
</td>
<td style="text-align:right;">
-1.816
</td>
<td style="text-align:right;">
0.163
</td>
<td style="text-align:right;">
0.937
</td>
</tr>
<tr>
<td style="text-align:left;">
initial_severity_level_code^6
</td>
<td style="text-align:right;">
-1.008
</td>
<td style="text-align:right;">
0.365
</td>
<td style="text-align:right;">
0.915
</td>
</tr>
<tr>
<td style="text-align:left;">
initial_severity_level_code^7
</td>
<td style="text-align:right;">
1.866
</td>
<td style="text-align:right;">
6.461
</td>
<td style="text-align:right;">
0.477
</td>
</tr>
<tr>
<td style="text-align:left;">
neighbourhoodchelsea and clinton
</td>
<td style="text-align:right;">
-0.678
</td>
<td style="text-align:right;">
0.508
</td>
<td style="text-align:right;">
0.000
</td>
</tr>
<tr>
<td style="text-align:left;">
neighbourhoodeast harlem
</td>
<td style="text-align:right;">
-0.340
</td>
<td style="text-align:right;">
0.712
</td>
<td style="text-align:right;">
0.002
</td>
</tr>
<tr>
<td style="text-align:left;">
neighbourhoodgramercy park and murray hill
</td>
<td style="text-align:right;">
-0.263
</td>
<td style="text-align:right;">
0.769
</td>
<td style="text-align:right;">
0.023
</td>
</tr>
<tr>
<td style="text-align:left;">
neighbourhoodgreenwich village and soho
</td>
<td style="text-align:right;">
-0.149
</td>
<td style="text-align:right;">
0.861
</td>
<td style="text-align:right;">
0.298
</td>
</tr>
<tr>
<td style="text-align:left;">
neighbourhoodinwood and washington heights
</td>
<td style="text-align:right;">
-0.037
</td>
<td style="text-align:right;">
0.964
</td>
<td style="text-align:right;">
0.722
</td>
</tr>
<tr>
<td style="text-align:left;">
neighbourhoodlower east side
</td>
<td style="text-align:right;">
0.003
</td>
<td style="text-align:right;">
1.003
</td>
<td style="text-align:right;">
0.975
</td>
</tr>
<tr>
<td style="text-align:left;">
neighbourhoodlower manhattan
</td>
<td style="text-align:right;">
-0.717
</td>
<td style="text-align:right;">
0.488
</td>
<td style="text-align:right;">
0.000
</td>
</tr>
<tr>
<td style="text-align:left;">
neighbourhoodupper east side
</td>
<td style="text-align:right;">
0.588
</td>
<td style="text-align:right;">
1.800
</td>
<td style="text-align:right;">
0.000
</td>
</tr>
<tr>
<td style="text-align:left;">
neighbourhoodupper west side
</td>
<td style="text-align:right;">
0.609
</td>
<td style="text-align:right;">
1.838
</td>
<td style="text-align:right;">
0.000
</td>
</tr>
</tbody>
</table>
<p>We demonstrate the odds of death on arrival for each of the variables used in the analysis.</p>




</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.header').parent('thead').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open')
  });
});
</script>

<!-- code folding -->


<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
