---
title: 'Final Project: Proposal'
author: "JACAB"
date: "11/6/2019"
output: github_document
---

### Group Members: 

* Jai Oberai (UNI:)

* Amelia Zhao (UNI:)

* Carolina Queiroz Cardoso (UNI:)

* Amanda Howarth (UNI:)

* Bing Bing Guo (UNI:BG2645)

### Tentative Project Title: 

* "Help! I've Fallen and Can't Get Up": EMS Response Times in NYC

### Motivation for Project: 

* 

### Intended Final Products: 
* Written Report 
* Webpage 
* Two-Minute Narrated Screencast
* Peer Assessment 

### Anticipated Data Sources: 
##### NYC EMS DATA: 
* EMS incident Dispatch Data generated by the EMS Computer Aided Dispatch System - obtained from NYC Open Data. 
https://data.cityofnewyork.us/Public-Safety/EMS-Incident-Dispatch-Data/76xm-jjuj

* Possible variables to explore: INITIAL_SEVERITY_LEVEL_CODE, FINAL_SEVERITY_LEVEL_CODE, DISPATCH_RESPONSE_SECONDS_QY, INCIDENT_TRAVEL_TM_SECONDS_QY, HELD_INDICATOR, BOROUGH, ZIPCODE 

##### NYC CENSUS DATA: 
* NYC Census Data to obtain demographic measures at the zipcode/borough level 


### Planned Analyses / Visualizations / Coding Challenges: 
* 

### Proposed Timeline: 
* November 7 by 1:00
