---
title: "Overview"
---
#
#

<font size="3">
It is expected that when it comes to emergency medical services (EMS), faster is always better. Most EMS operations aim to have a response time of 8 minute or less for advanced life support (ALS) units responding to life-threatening events.

In 2018, it was estimated that [~46 percent of ambulance responses to serious emergencies took longer than 10 minutes in NYC](https://cbcny.org/research/reviving-ems). The City of New York spends more than [$1.1 billion annually to provide EMS services](https://council.nyc.gov/budget/wp-content/uploads/sites/54/2018/03/FY19-Fire-Department-of-New-York.pdf) to the city, however the money is often not used wisely. Conflicting reports claiming that an 8 minute or less response time may not improve health outcomes call into question whether a response time <8 min is important and if we should we allocate more funds to reduce NYC response times.

This study seeks to assess the association between NYC EMS response time and mortality. A detailed explanation of the findings and conclusions of this project can be found in the Project Report, [here](report.html).


<h2> Dataset </h2>

We used the [EMS Incident Dispatch Data](https://data.cityofnewyork.us/Public-Safety/EMS-Incident-Dispatch-Data/76xm-jjuj) dataset, generated by the EMS Computer Aided Dispatch System. The data was obtained from NYC Open Data.

The data spans from the time the incident is created in the system to the time the incident is closed in the system. It covers information about the incident as it relates to the assignment of resources and the Fire Department’s response to the emergency.

_(To protect personal identifying information in accordance with the Health Insurance Portability and Accountability Act (HIPAA), specific locations of incidents are not included and have been aggregated to a higher level of detail.)_

For every call/emergency in the system from the start of 2013 to the end of 2018, the database contains information on the following components: 

* Time (initial, closing)

* Call/emergency type (initial, closing, severity)

* Location (borough, dispatch area, zip code, precinct, district (city council, community, school, congressional))

* Response time (incident, dispatch)

As well as some internal quality control measures.

We narrowed down the original 8.56 million rows of data, based on the following:

* Borough: Manhattan
* Year: 2018
* Valid incident response time (quality control)
* Only non-cancelled calls
* No duplicate calls
* Only calls where EMS was dispatched
* Only calls where the final clinical outcome was not missing or unknown

And after separated the date and time variables, recoded relevant variables as factors, created a clinical outcome variable regarding living status, created a neighborhood variable based on zip code using the [New York State Department of Health ZIP Code Definitions of New York City Neighborhoods](https://www.health.ny.gov/statistics/cancer/registry/appendix/neighborhoods.htm), and excluded missing values. 

</font>