---
title: "**Help! I've Fallen and I Can't Get Up: A Report**"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)

library(tidyverse)
```

*Note: The title of this project is a line from a commercial that has been [memed](https://www.google.com/search?q=life+alert+meme&sxsrf=ACYBGNQqIvW74KMRbdauXsERsqWnXo-X_Q:1575226120265&source=lnms&tbm=isch&sa=X&ved=2ahUKEwiWjdvKjpXmAhVHq1kKHccFBD8Q_AUoAXoECAsQAw&biw=1130&bih=1257) and is often the subject of jokes. It is in no way meant to trivialize the emergencies experienced by 911 callers or the work of EMS responders. 




## **Motivation and Project Goals**

In New York City, emergencies abound. It’s hard to imagine a day in New York without the sound of wailing sirens and flashing emergency vehicle lights. 

It is expected that when it comes to emergency medical services (EMS), faster is better. Most EMS operations aim to have a response time of 8 minute or less for advanced life support (ALS) units responding to life-threatening events.

In 2018, it was estimated that [~46 percent of ambulance responses to serious emergencies took longer than 10 minutes in NYC](https://cbcny.org/research/reviving-ems). The City of New York spends more than [$1.1 billion annually to provide EMS services](https://council.nyc.gov/budget/wp-content/uploads/sites/54/2018/03/FY19-Fire-Department-of-New-York.pdf) to the city, however the money is often not used wisely. Conflicting reports claiming that an 8 minute or less response time may not improve health outcomes call into question whether a response time <8 min is important and if we should we allocate more funds to reduce NYC response times.

This study seeks to assess the association between NYC EMS response time and mortality.




## **Related Work/Inspiration**
When thinking about the direction for our project, our group considered past years' projects to help create an image of our end product. In looking at these projects, we found that a lot of groups focused on local, NYC-based phenomena. We thought it would be great to take a deeper look at the city that is our home. 

Multiple data sources were considered, but the choice to examine Emergency Medical Services was unanimous and immediate. We tapped into our knowledge from the Core and immediately thought of the differences in health determinants, infrastructure, and accessibility between Manhattan neighborhoods. 



## **Initial Questions**
After a very preliminary glance at the data set, some of the proposed questions were:

* Do different types of EMS calls get treated differently?
* Are response times different for different types of calls?
* Do response times vary by borough, zip code, or neighborhood?
* Could geographical resources and income associated with neighborhoods be associated with response time?

We wanted to examine a possible relationship between socio-economic status (SES) and response time/clinical outcome. However, finding a good proxy for SES proved to be difficult. Variables we considered were annual income, monthly rent, education, or occupation. In the end, we didn't feel that any of these could very accurately represent SES, and that even within neighborhoods that are typically "wealthy" or "poor", outliers or unreliable data would likely skew the results. Data for these variables was hard to find. For the data we did find, we were not confident that the data sources for these variables were completely accurate due to unreliable reporting methods.

We wanted to examine whether there were points in the FDNY EMS Response system that may be vulnerable to bias or mistakes, where further research could shape interventions to improve emergency responses.  Thus, we decided to explore the relationships between neighborhood, response time, and clinical outcome, posing the following questions:

* Do clinical outcomes differ by neighborhood?
* Do clinical outcomes vary depending on the nature of the emergency?
* Does response time vary depending on the nature of the emergency?
* Does response time differ by neighborhood?

Later on, due to computing restraints, we limited our analysis to the borough of Manhattan. We all have a personal connection to Manhattan as we live and go to school here, and we felt that it has a very diverse range of neighborhoods. 



## **Data**
The data source for this project comes from the [NYC EMS Incident Dispatch Data](https://data.cityofnewyork.us/Public-Safety/EMS-Incident-Dispatch-Data/76xm-jjuj), owned by NYCOpenData and provided by the Fire Department of New York City.

The EMS Incident Dispatch Data is generated by the FDNY EMS Computer Aided Dispatch System. The data spans from the time an incident is created in the system to the time that incident is closed. 

For every call/emergency in the system from the start of 2013 to the end of 2018, the database contains information on the following components: 

* Time (initial, closing)

* Call/emergency type (initial, closing, severity)

* Location (borough, dispatch area, zip code, precinct, district (city council, community, school, congressional))

* Response time (incident, dispatch)

As well as some internal quality control measures. 

As noted, to protect personal identifying information in accordance with the Health Insurance Portability and Accountability Act (HIPAA), specific locations of incidents are not included and have been aggregated to a higher level of detail.

Additionally, for the assignment of neighborhood by zip code, we used the [New York State Department of Health ZIP Code Definitions of New York City Neighborhoods](https://www.health.ny.gov/statistics/cancer/registry/appendix/neighborhoods.htm).

### Cleaning
The original dataset contains 8.56 million rows of data, spanning across 5 years. 
Due to computing restraints, we narrowed down the dataset before cleaning it in RStudio. We applied the following constraints to the dataset:

* Borough: Manhattan
* Year: 2018
* Valid incident response time (quality control)
* Only non-cancelled calls
* No duplicate calls
* Only calls where EMS was dispatched
* Only calls where the final clinical outcome was not missing or unknown

After we limited the data set, data cleaning steps included separating the date and time variables, recoding relevant variables as factors, creating a clinical outcome variable regarding living status, creating a neighborhood variable based on zip code, and excluding missing values. 

## **Exploratory analysis**






### Death Counts by Month
There seems to be a slight seasonal trend in the number of those who are deceased upon arrival of the EMS Response Team, with peaks during the summer and winter. There was a 34% decrease in the number of deaths between January, the month with the most, and September, the month with the least. 




## **Statistical analysis**






## **Results & Discussion**

The data seem to suggests a seasonal trend in the number of individuals deceased upon arrival of EMS Response Teams. However, it is unclear whether this trend is consistent from year-to-year. 


### Strengths & Limitations

Our study was able to efficiently and clearly assess the relationship between 

One of the biggest limitations of our study is that the data did not contain a variable indicating the type of response unit sent. The FDNY is in command of many different response units, which all correspond to different types of emergencies.

Additionally, the data is only recorded once the incident is created in the FDNY system. If you’ve ever called 911 (hopefully you haven’t had to), you’ll know that the first person you talk to is not a police officer, emergency medical technician, or fire fighter. It’s a 911 Call Taker, as shown by this schematic provided by [NYC Analytics](http://home2.nyc.gov/html/911reporting/html/anatomy/call.shtml). These call takers ask tons of questions, the most notable being “What’s your emergency” to assess the appropriate emergency response team for the situation. A police officer may not be as helpful as a firefighter for a building fire.

After the dispatcher determines the best response team for the emergency, they will either put you directly in contact with someone from say, the fire department or police, or they will pass the information along to them while they stay on the line with you. (In the NYC Analytics [schematic](http://home2.nyc.gov/html/911reporting/html/anatomy/call.shtml), this is shown under FDNY EMS VESTA in Orange as 911 Call Conference). Then, either the caller or call taker may have to relay the pertinent information to the response team dispatcher.

Our data is collected only after the first 911 call taker has passed the call along to the FDNY EMS (Incident creation in the [schematic](http://home2.nyc.gov/html/911reporting/html/anatomy/call.shtml)). Thus, it does not include the amount of time the caller spent explaining their emergency to the dispatcher before being transferred to the FDNY. In many cases, this can be a lengthy process, but from our data it is impossible to tell. Additionally, it is unclear from the data whether, from the NYC Analytics schematic, whether our incident creation is at the general incident creation between “Call Taking” and “Skip to Dispatch” in yellow at the top, or the “EMS Incident Creation” between “911 Call Conference” and “Dispatch Queue” in orange at the bottom of the schematic.

911 calls are emergencies, so time is crucial. The time before the incident is created could influence not only the resulting morbidity or mortality of those involved in the emergencies, it could also influence the amount of time the FDNY spends on the phone before a unit is dispatched. For example, if the 911 caller is in some way incapacitated, the initial call taker may have difficulties assessing the emergency and identifying the appropriate response team. The FDNY EMS dispatcher may also then have difficulties assessing what type of unit to send, or even where to send the unit.

As a result, the data provide indications of the efficiency of the EMS Response Teams in each neighborhood, but not necessarily the safety or other inherent traits thereof. 

Another limitation to our data is that it was only collected from 2018. Amid political unrest regarding our current President and his legal affairs, Supreme Court Judge pick, and immigration policies; unhappiness with NYC's current mayor; and mass shootings rocking the nation, this year could have seen an increase in violent crime or substance abuse, skewing the results. Conversely, compared to the election year of 2016, crime and substance abuse could have dropped significantly. We cannot extrapolate our findings to years past or present.

### **Conclusion**

The distributions of those deceased upon arrival of EMS Response Teams and travel time may be affected by a number of external factors. Future research comparing political climate, extreme weather, or local cultural events to multiple years of data may provide more insight into the reasoning for the variation seen in our data. 




